AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  HealthMonitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./cmd/
      Handler: health-monitor
      Runtime: provided.al2
      Architectures:
        - x86_64
      Timeout: 20 # maximum function execution time (seconds) - AWS default is 3 seconds
      MemorySize: 128 # more memory = higher cost, better performance - AWS minimum memory allocation is 128MB
      ReservedConcurrentExecutions: 1 # how many instances of the Lambda that can run at once
      Events:
        ScheduledCheck:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
      Environment:
        Variables:
          # reference parameters stored in AWS Systems Manager
          SITES_TO_MONITOR: "{{resolve:ssm:/backend/lambda/sites-to-monitor}}"
          SERVERS_TO_MONITOR: "{{resolve:ssm:/backend/lambda/servers-to-monitor}}"
          NOTIFICATION_SERVER_ENDPOINT: "{{resolve:ssm:/backend/lambda/notification-server-endpoint}}"
          EMAIL_NOTIFICATION_RECIPIENTS: "{{resolve:ssm:/backend/internal/alert-emails}}"
          BACKEND_API_KEY: "{{resolve:ssm:/backend/internal/api-key}}"
