AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  SiteMonitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./cmd/health-monitor/
      Handler: health-monitor
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        ScheduledCheck:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
      Environment:
        Variables:
          # reference parameters stored in AWS Systems Manager
          SITES_TO_MONITOR: "{{resolve:ssm:/backend/lambda/sites-to-monitor}}"
          SERVERS_TO_MONITOR: "{{resolve:ssm:/backend/lambda/servers-to-monitor}}"
